Add recipe app
Tamanna-S/javaScript-projects pull request #83
Opened 2022-10-11 17:03 UTC by rjrishika

2022-10-11 17:03 UTC, rjrishika commented
please add this project under hacktoberfest

2022-10-12 05:30 UTC, Tamanna-S commented
remove it from basic projects and add readme with ss or short video

2022-10-13 11:24 UTC, rjrishika commented
add readme  and remove from basic project

2022-10-13 12:49 UTC, alicalimli requested changes
Nicely done!

2022-10-13 16:41 UTC, merged